### ISSUE TITLE
Example needed: running Ruby code in Chrome

### ISSUE THREAD

**Issue by c4lliope** [ruby/ruby.wasm#10]
Hello all - I'm glad to be back in a Ruby codebase after so long dealing with Javascript.

My goal is to combine these two languages by enabling the running of Ruby code from inside a webpage.
Here is my approach so far:

```javascript
import { WASI, init } from '@wasmer/wasi'

var main = async () => {
  await init();

  let wasi = new WASI({
    env: {},
    args: ['ruby -e "puts 0"'],
  });

  console.log(1)
  const moduleBytes = fetch("/processors/ruby+stdlib.wasm");
  const module = await WebAssembly.compileStreaming(moduleBytes);

  console.log(2)
  // Instantiate the WASI module
  await wasi.instantiate(module, {});

  console.log(3)
  // Run the start function
  let exitCode = wasi.start();
  let stdout = wasi.getStdoutString();

   // This should print "hello world (exit code: 0)"
  console.log(`${stdout}(exit code: ${exitCode})`);
}

main()
```

I am running this code, packaged up by `webpack`, with a polyfill for `Buffer`.
I based my code on https://wasmer.io/posts/wasmer-js-a-new-hope -
the example there uses the WASM binary https://deno.land/x/wasm@v1.0.0-alpha4/tests/demo.wasm,
which runs properly in my code.

Sadly, changing the binary to `ruby+stdlib.wasm` produces an error:
```
[application.js:16:10](webpack://app/src/application.js)
Uncaught (in promise) Error: Failed to instantiate WASI: RuntimeError: `
```

My main goal is to be able to pass a measure of Ruby code into the Ruby WASI process,
and use the response inside my webpage.
I am happy to use the `memfs` filesystem for recording and passing in my Ruby programs,
so long as the approach enables me to send in any Ruby code I like with no precompilation.

This may be an ambitious goal; though I imagine this could become a necessary use case for many people.

**Comment by c4lliope** [comment]
You can read, clone, and run my code from https://base.assembled.app/c4lliope/ruby-engine.0/

**Comment by kateinoigakukun** [comment]
@c4lliope Thank you for reporting :)

Unfortunately, the latest version 1.x WASI polyfill provided by wasmer is broken. I've fixed several issues for the project, but it still has issues and also not actively maintained by the maintainers. So I have no plans to fix or support version 1.x of `@wasmer/wasi` package anymore. Sorry.

Please use version 0.x family for now 🙏  This is one of the important topic not only for ruby but also for other communities, so we need to figure out how to deal with this.

**Comment by kateinoigakukun** [comment]
@c4lliope Thank you for reporting :)

Unfortunately, the latest version 1.x WASI polyfill provided by wasmer is broken. I've fixed several issues for the project, but it still has issues and also not actively maintained by the maintainers. So I have no plans to fix or support version 1.x of `@wasmer/wasi` package anymore. Sorry.

Please use version 0.x family for now 🙏  This is one of the important topic not only for ruby but also for other communities, so we need to figure out how to deal with this.

**Comment by c4lliope** [comment]
I'll do a closer examination of the example made by https://github.com/ongaeshi/rubyonbrowser,
based on `@wasmer/wasi @ 0.12.0`.

Seems like the three examples on https://docs.wasmer.io/integrations/js/wasi/browser
are also keyed for the `0.12.0` release of the library.
