### ISSUE TITLE
How to pass non primitive Ruby constructs to JS

### ISSUE THREAD

**Issue by scally** [ruby/ruby.wasm#115]
I've been working with using React from ruby.wasm, and came across some issues trying to pass things like Arrays and Ruby procs to JS.

Here's an example with arrays, for instance:
```
map_call = JS.eval <<-JS
  return {testMap: function(arr) {
    arr.forEach(i => console.log(i))
  }}
JS
map_call.call :testMap, [1, 2, 3]
```

This fails with the error "argument 2 is not a JS::Object like object".

I can get it working with something like this:
```
class Array
  def to_js
    JS.global.call :Array, *self
  end
end
```

Is this intended? Is ruby.wasm in need of more functionality to handle more than just raw String/Int/Bool args being passed to JS? Or is it intended to be something another external library adds? Or is there a simpler way to be doing this?

(I am having the same troubles with passing Procs)

**Comment by scally** [comment]
Adding the additional repro for proc:

```
test_proc = proc do |x|
  x + 1
end

test_caller = JS.eval 'return {a(cb) { cb(10) } }'
puts test_caller.a test_proc
```

result: `undefined method `+' for 10:JS::Object`

**Comment by kateinoigakukun** [comment]
Sorry for my slow reply :bow:
How about passing the object as `RbValue` by `JS::Object.wrap`? like

```ruby
map_call = JS.eval <<-JS
  return {testMap: function(arr) {
    const length = value.call("length").toJS();
    for (let i = 0; i < length; i++) {
      const element = value.call("at", vm.eval(String(i)));
      console.log(element.toString())
    }
  }}
JS
map_call.call :testMap, JS::Object.wrap([1, 2, 3])
```

But apparently, we should have a better API for this case. I think the js library is responsible to handle this.

**Comment by scally** [comment]
Yes, it seems like in the current implementation, if you called an existing JS package it would not work since the called function would need to have the knowledge of unwrapping the Ruby object. This would keep Ruby.wasm from having compatibility with existing JS code since it's a common pattern to pass functions and callbacks to JS libraries.

Thanks for your response
