### ISSUE TITLE
[ruby-head-wasm-wasi] Is there any way to disable `js` module?

### ISSUE THREAD

**Issue by riywo** [ruby/ruby.wasm#126]
I'd like to use `ruby.wasm` as a sandboxed interpreter in browser i.e. just for pure computation with restricted DOM access because it executes untrusted code.

It looks like `js` module is available by default in `ruby-head-wasm-wasi`'s `DefaultRubyVM`, but is there any way to disable it?
https://github.com/ruby/ruby.wasm/tree/main/packages/npm-packages/ruby-head-wasm-wasi#quick-start-for-browser

I'm a novice in the WebAssembly world, so it'll take time to read the whole code base of `ruby.wasm` for me. Therefore, I'm asking such a question beforehand in case someone already knows the answer...

Sorry for bothering you guys.

**Comment by kateinoigakukun** [comment]
Thank you for opening an interesting topic!
If you need only need Ruby interpreter, you don't need `ruby-head-wasm-wasi` package at all. You can use non `-js` suffixed artifacts like below:

1. Install browser compatible WASI implementation:
```
$ npm install uwasi
``` 

2. Download ruby.wasm binary that does not link js extension

```
$ curl -L curl -L https://github.com/ruby/ruby.wasm/releases/download/2022-12-02-a/ruby-head-wasm32-unknown-wasi-minimal.tar.gz | tar xz --strip-components=1
```

3. Setup JS code to launch WASI app
```js
import { WASI, useAll } from "uwasi";

async function main() {
    const wasi = new WASI({
        args: ["ruby.wasm", "-e", "puts :Hello"],
        features: [useAll()],
    });
    const response = await fetch("./usr/local/bin/ruby.wasm");
    const buffer = await response.arrayBuffer();
    const { instance } = await WebAssembly.instantiate(buffer, {
        wasi_snapshot_preview1: wasi.wasiImport,
    });
    const exitCode = wasi.start(instance);
    console.log("exit code:", exitCode);
}

main()
```

**Comment by riywo** [comment]
Amazing! That's a nice idea.

Just curious: Where is this `js` module implemented? I might need a custom module to import some JS functionality to the ruby world, so I wonder where I can refer the `js` module.

**Comment by kateinoigakukun** [comment]
The `js` extension is implemented here: https://github.com/ruby/ruby.wasm/tree/main/ext/js
If you want to import some of functionalities from outside of the Wasm program (it means importing from JS on browser), you can add `import` entries like:

https://github.com/ruby/ruby.wasm/blob/802ecc5047ac9ee7270b58e7f11cea87b8172f36/ext/js/bindgen/rb-js-abi-host.c#L78-L79

You need to write your own C extension to import them, and you need to change [Rakefile](https://github.com/ruby/ruby.wasm/blob/802ecc5047ac9ee7270b58e7f11cea87b8172f36/Rakefile#L92-L118) to build and link it into ruby.wasm

**Comment by riywo** [comment]
I really appreciate your kind responses. I'll try to integrate `ruby.wasm` with my project!
