### ISSUE TITLE
[ruby-head-wasm-wasi] Feature request to customize default import functions

### ISSUE THREAD

**Issue by riywo** [ruby/ruby.wasm#127]
Related to https://github.com/ruby/ruby.wasm/issues/126

I have looked around the code and the current JS extension is really impressive. The problem for me is I want to use subset of its capabilitiies for security concerns.

As far as I understand, it looks like this is the final list of the default import functions to WebAssembly and if we omit a function from here, the ruby side's JS extension will fail because there are no associated JS functions:
https://github.com/ruby/ruby.wasm/blob/802ecc5047ac9ee7270b58e7f11cea87b8172f36/packages/npm-packages/ruby-wasm-wasi/src/index.ts#L83-L199

For example, if I remove `evalJs` here, `JS::eval` in ruby fails, which is ideal for me.

For security concerns, `evalJs` and `globalThis` needs more control. Therefore, I'm wondering whether we can add an option to customize these default import functions. The interface might look like:

```javascript
const { vm } = await DefaultRubyVM(module, {
  importEvalJs: false,  // I don't want to allow `JS::Eval`
  importGlobalThis: ["Promise"],  // I don't want to allow to access `document`, etc., but `Promise` to use `.await` in the JS extension
});
```

Or, more transparent to the import functions definition:

```javascript
const { vm } = await DefaultRubyVM(module, {
  imports: { // Override default imports if the field has the same name.
    evalJs: (code) => {
      throw new Error("Not supported");
    },
    globalThis: () => {
      if (typeof globalThis !== "undefined") { 
        return { Promise: globalThis.Promise }; 
      } else if (typeof global !== "undefined") { 
        return { Promise: global.Promise }; 
      } else if (typeof window !== "undefined") { 
        return { Promise: window.Promise }; 
      }
      throw new Error("unable to locate global object");  
    },
    // Other functions are imported untouched.
  }
});

```

I imagine some functionalities rely on the others, so these options might not be such simple, but how does this sound to you? If it looks good, I can work on a PR. These changes are only inside JS code and no need to touch wasm side at all.

I believe there are some use cases to allow the customers to run arbitrary program code inside a secure sandbox and WebAssembly is really useful for this because it can control which JS functionality is exposed to WebAssembly and vice versa. I hope this could help not only me but also some others.

**Comment by kateinoigakukun** [comment]
Yeah, I think it's an interesting sandbox use case in browsers. But limiting access to the global object is still vulnerable.
In your example, users can retrieve only the Promise object from the global object, but they can easily pollute Promise object in Ruby like below:

```ruby
require "js"
JS.global[:Promise][:prototype][:then] = proc do
  puts "faked"
end
```

I'm not a security expert in JavaScript, so I think there should be more critical issues I haven't figured out.
Therefore, I think it's very difficult to reuse the `js` extension for secure sandbox purpose.
Just FYI: Figma's plugin system stories would be interesting for you:
- [How to build a plugin system on the web and also sleep well at night](https://www.figma.com/blog/how-we-built-the-figma-plugin-system/)
- [An update on plugin security](https://www.figma.com/blog/an-update-on-plugin-security/)

Then, my suggestion is "Don't expose JS language operations. Expose functions statically". This is often used sandbox strategy in WebAssembly products.

You can refer Fastly's Compute@Edge interface as an example.
https://github.com/kateinoigakukun/ruby-compute-runtime/blob/main/ext/compute_runtime/compute_runtime.c

**Comment by riywo** [comment]
Thank you again for valuable information. The Figma's architecture is very similar to what I want to do.

For my use case, I'd like to just expose a blocking (or non-blocking) call to wait until a specific message (response) is received after an initial message is sent (request) to emulate network communication inside browser's JavaScript with sandbox.

I was wondering to implement a simple polling logic inside Ruby extension using an imported JS function "poll" to just check the message's arrival status to wait the response on Ruby side, but since it blocks entire WASM execution, it requires to run inside Web Worker, which is good but I was also looking for a simpler solution. The ruby.wasm has [`await`](https://github.com/ruby/ruby.wasm/blob/main/ext/js/lib/js.rb#L122-L126) functionality so that I thought I could run it inside the main thread.

However, as you mentioned, minimizing the scope is much better. Let me explore the options with the C extension.

**Comment by kateinoigakukun** [comment]
@riywo `await` and `PromiseScheduler` is very simple, so you can imitate them for your specific usecase easily.
