### ISSUE TITLE
Npm publish of nightly release is failing since 2022-05-21

### ISSUE THREAD

**Issue by keyasuda** [ruby/ruby.wasm#19]
There're no nightly npm packages newer than 2022-05-18 on [NPM](https://www.npmjs.com/package/ruby-head-wasm-wasi), and it seems that the nightly release action is failing to publish.
https://github.com/ruby/ruby.wasm/runs/6527649310?check_suite_focus=true#step:6:31

Probably similar to this https://github.com/semantic-release/npm/issues/209 issue, there're something wrong with the `NODE_AUTH_TOKEN`. Would you check it?

**Comment by kateinoigakukun** [comment]
I haven't realized that situation. Thank you for letting me know!
I've updated the token and I hope it makes the automation back. Will close after today's nightly release.

**Comment by keyasuda** [comment]
Thank you!

**Comment by kateinoigakukun** [comment]
OK, it works now again 👍
