### ISSUE TITLE
The nightly releases on the CDN are unavailable

### ISSUE THREAD

**Issue by woxtu** [ruby/ruby.wasm#20]
Hi,

Unfortunately the nightly releases on the CDN are unavailable now.
e.g. https://www.jsdelivr.com/package/npm/ruby-head-wasm-wasi?version=0.3.0-2022-05-31-a

Do you have any plans to resolve that?

**Comment by kateinoigakukun** [comment]
Thank you for letting me know! I haven't noticed that situation.
I've made a patch to address this issue.

**Comment by woxtu** [comment]
Thank you for your quick response. I'm looking forward to the next release.

**Comment by woxtu** [comment]
Looks good, thanks again.
