### ISSUE TITLE
`new` operator support in `js` library

### ISSUE THREAD

**Issue by kateinoigakukun** [ruby/ruby.wasm#207]
### Discussed in https://github.com/ruby/ruby.wasm/discussions/165

<div type='discussions-op-text'>

<sup>Originally posted by **scally** February 14, 2023</sup>
How do you call `new` on Javascript objects? I haven't found a workaround yet that will let me do this. I can call the object constructor but it will then tell me that I need to call the `new` operator:

for example:
```
observer = JS.global.MutationObserver do
  puts 'here'
end
```
results in 
```
TypeError: Constructor requires 'new' operator (JS::Error)
```</div>

**Comment by SatorSight** [comment]
Couldn't find proper Ruby solution, so had to use:
`offset_canvas = JS.eval('return new OffscreenCanvas(1, 2)')`
This at least properly returns usable object.

**Comment by kateinoigakukun** [comment]
Closed by https://github.com/ruby/ruby.wasm/pull/246
