### ISSUE TITLE
"SystemStackError: stack level too deep" when requiring json with latest built ruby-3_2-wasm-wasi

### ISSUE THREAD

**Issue by scally** [ruby/ruby.wasm#234]
Repro:
- build `rake npm:ruby-3_2-wasm-wasi:build` locally with prebuilt rubies
- create html file like this referencing built package
```
<!DOCTYPE html>
<html>

<head>
  <title>rwasm test</title>
</head>

<body>
</body>
<script src="ruby-3_2-wasm-wasi/dist/browser.script.iife.js"></script>
<script data-eval="async" type="text/ruby">
  require 'json'
</script>


</html>
```

Error:
`Unhandled Promise Rejection: Error: SystemStackError: stack level too deep`

Removing `require json` or `data-eval="async"` fixes the problem. 
Theory: Is it due to some kind of lack of thread safety in the original CRuby json lib?

**Comment by kateinoigakukun** [comment]
Thank you for trying the new feature! https://github.com/ruby/ruby.wasm/pull/235 will resolve the issue. Could you try again after the the PR will be merged?

**Comment by scally** [comment]
@kateinoigakukun It works now. Thanks!
