### ISSUE TITLE
Handle JS null values within Ruby code

### ISSUE THREAD

**Issue by richardboehme** [ruby/ruby.wasm#24]
Hey, thanks for providing those great NPM packages!

I'm currently experimenting with writing DOM-Interaction using the JS interoperability module that this package provides. I wonder if it's possible to handle null values with the JS module?

I try to read from localStorage and if a key was not set `localStorage.getItem` will return `null`. This `null` value gets wrapped into a `JS::Object` which isn't really useful because all reflection methods complain that `null` is not an object. Could we return `nil` instead or add a method to `JS::Object` to identify it being `null`?

My example:

```ruby
null_value = JS::global[:localStorage].call('getItem', 'foobar')
p null_value.inspect
# => Uncaught TypeError: Cannot read properties of null (reading 'toString')
```

I'm happy to help, just not sure how we should approach this.

**Comment by kateinoigakukun** [comment]
Thank you for reporting!
I think there are 2 topics in your comment.

1. Inspection against `null` causes `TypeError: Cannot read properties of null`
2. Implicit conversion from JS `null` to Ruby `nil`

The first one is apparently a bug in this library. I've made [a patch](https://github.com/ruby/ruby.wasm/pull/25) to fix it. I hope it will solve it.

The second one is a little bit difficult topic around API design. I'm happy to introduce such a conversion in the future, but I'm not confident about its design. For example, if `null` is implicitly converted into `nil`, then what should we do for `undefined`?
It would be longer discussion, so I would like to focus on the 1. bug in this ticket. Feel free to open another issue to discuss the design choice if you want.

**Comment by richardboehme** [comment]
Thank you for coming back and fixing `inspect`! I think we also have to add null-checks to other methods. For example `JS::Object#call` would throw if the object is `null`.

I'm going to open a discussion about the second point you mentioned!

**Comment by richardboehme** [comment]
(Started a discussion in #26)

**Comment by kateinoigakukun** [comment]
> Thank you for coming back and fixing inspect! I think we also have to add null-checks to other methods. For example JS::Object#call would throw if the object is null.


Hmm, I think it's expected behavior. What the expected behavior when calling method where the receiver is null?

**Comment by richardboehme** [comment]
> Hmm, I think it's expected behavior. What the expected behavior when calling method where the receiver is null?

Hm you may be right. Maybe I was just confused from the error message at first:

```
null_value = JS::eval('return null')
null_value.call('foobar')
# Uncaught TypeError: Reflect.get called on non-object
```

Maybe the idea would be to improve the error message? Maybe it's not necessary though.

**Comment by kateinoigakukun** [comment]
Ah, I see. It makes sense to stop using `Reflect.get` to improve error message.
