### ISSUE TITLE
Page crashes on iOS Safari and Chrome when using ruby-head-wasm-wasi@latest

### ISSUE THREAD

**Issue by yancya** [ruby/ruby.wasm#273]
## Description
When I open a webpage that includes the https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@latest/dist/browser.script.iife.js script, the page crashes on iOS browsers like Safari and Chrome. However, changing to https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@2.0.0/dist/browser.script.iife.js resolves the issue and the page no longer crashes.

## Steps to reproduce
Load a webpage that includes https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@latest/dist/browser.script.iife.js.
Open the page in iOS Safari or Chrome.

## Expected behavior
The page should load and function normally.

## Actual behavior
The page crashes upon loading.

## Environment
iOS version: 16.6

**Comment by unasuke** [comment]
In my investigation, the cause is in these diff https://github.com/ruby/ruby.wasm/compare/2023-05-20-a...2023-05-21-a

And iPadOS didn't crash. Crashes only iOS Safari.

**Comment by ledsun** [comment]
It was also reproduced on an Android device, a motorola moto g31 with Google Chrome.

I opened `packages/npm-packages/ruby-wasm-wasi/example/hello.html` and found the following error:
![image (3)](https://github.com/ruby/ruby.wasm/assets/1079508/326b503f-daee-4217-8cd3-d7d34dd73016)

I re-built `browser.script.iife.js` with `RUBY_FIBER_MACHINE_STACK_SIZE` set to `8388608` and `hello.html` worked fine.
Rebuild was done with `rake npm:ruby-head-wasm-wasi`.

`8388608` is half of the [current value](https://github.com/ruby/ruby.wasm/blob/a7c09b8d2c10bdb8e5b19b0b4e5a012b810f778d/packages/npm-packages/ruby-wasm-wasi/src/browser.ts#L79).
I do not know if this value is appropriate.
