### ISSUE TITLE
Export WASM_FILE_PATH from @ruby/3.2-wasm-wasi and @ruby/head-wasm-wasi

### ISSUE THREAD

**Issue by terrablue** [ruby/ruby.wasm#338]
In the cheat sheet, this line is used:

```
const binary = await fs.readFile("./node_modules/@ruby/3.2-wasm-wasi/dist/ruby.wasm");
```

That's a bit flaky and would break if you moved this file elsewhere.

Would it be possible to export a WASM_FILE_PATH from @ruby/3.2-wasm-wasi and @ruby/head-wasm-wasi such that it is a resolved absolute path to the Wasm binary?

The NodeJS cheat sheet would then look like this:

```
import fs from "fs/promises";
import { DefaultRubyVM } from "@ruby/wasm-wasi/dist/node";
import { WASM_FILE_PATH } from "@ruby/3.2-wasm-wasi"; // or from "@ruby/head-wasm-wasi"

const binary = await fs.readFile(WASM_FILE_PATH);
const module = await WebAssembly.compile(binary);
const { vm } = await DefaultRubyVM(module);
vm.eval(`puts "hello world"`);
```

Could this be considered?

**Comment by terrablue** [comment]
You can retain backwards compatibility by keeping the files where they are and just having the abstraction point to the right path. Or break compatibility with your next major.

I'm not really aware of comparable examples in the JavaScript, where one package provides the 'environment' and another a piece of data to be loaded into that environment. It might be an oddly specific Wasm-related constellation. But hard-coding paths isn't common, as far as I'm aware.

FWIW, I'm using the `pyodide` package for Python Wasm, and there there is just one export which takes of everything. But I'm not sure that's applicable to this situation, where you can alternate between 3.2 and head.

**Comment by kateinoigakukun** [comment]
Closed by https://github.com/ruby/ruby.wasm/pull/372
