### ISSUE TITLE
ruby_wasm fails to install on Rust 1.75

### ISSUE THREAD

**Issue by palkan** [ruby/ruby.wasm#369]
Building native extensions on Rust 1.75.0 fails due to this bug: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276033

Downgrading to 1.74.0 helps.

P.S. I think, this issue can be closed right away. Just wanted to warn other ruby.wasm newcomers about this potential problem 🙂.

**Comment by kateinoigakukun** [comment]
Thank you for trying this project :)
I think we've fixed the issue by https://github.com/ruby/ruby.wasm/pull/364, doesn't it work? In that case, which revision of ruby.wasm are you building for?

**Comment by palkan** [comment]
Here is my environment:

- ruby_wasm: 2.5.0.pre.1
- ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]

**Comment by kateinoigakukun** [comment]
The latest 2.5.0 release contains a fix for this
