### ISSUE TITLE
[FAQ] Primary authors and / or maintainers

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/ruby.wasm#405]
Would it be possible to add to the FAQ the primary authors and / or current maintainers?

Just so people know who they could correspond with, if a need arises to do so. Right now
I do not know who created the project and/or maintains it. Thus a FAQ entry may be
useful for that.

**Comment by kateinoigakukun** [comment]
You can find such information in the [`.gemspec`](https://github.com/ruby/ruby.wasm/blob/84dfd762478cf393cf893d57b279e538e78a1c90/ruby_wasm.gemspec#L8) and I think it's very common convention to check the file
