### ISSUE TITLE
[FAQ] How to find out the most recent URL to ruby wasm browser.script.life.js?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/ruby.wasm#407]
Hey there,

The README here shows the current wasm .js file at:

    <script src="https://cdn.jsdelivr.net/npm/@ruby/3.3-wasm-wasi@2.5.0/dist/browser.script.iife.js"></script>

Is there a way to find out the latest URL? Ideally programmatically as well. In my own projects I may tend
to use constants for that, at the least for e. g. VERSION, so if 2.5.0 is the version of wasm perhaps we can
query it too (I don't even know where it resides right now... is the module called JS? Is there even such a
module?).

**Comment by kateinoigakukun** [comment]
```
<script src="https://cdn.jsdelivr.net/npm/@ruby/3.3-wasm-wasi@latest/dist/browser.script.iife.js"></script>
```

I think it works for you
