### ISSUE TITLE
Error requiring bundler

### ISSUE THREAD

**Issue by delbetu** [ruby/ruby.wasm#423]
I'm getting this error:
<img width="1181" alt="image" src="https://github.com/ruby/ruby.wasm/assets/3356799/113e4283-3b69-42ee-b3be-7b4e85a01df1">

when including this script:
```html
   <script src="https://cdn.jsdelivr.net/npm/@ruby/wasm-wasi@latest/dist/browser.umd.js"></script>
```

I think this: https://github.com/ruby/ruby.wasm/blob/669e98812dcea62f2f116da3f0f7837b7ef80d05/packages/npm-packages/ruby-wasm-wasi/src/vm.ts#L93

should say:

```javascript
    this.eval(`require "bundler/setup"`);
```

**Comment by kateinoigakukun** [comment]
The line itself is correct. There is `/bundle/setup.rb` if the given .wasm binary is packaged with `rbwasm build` command. Which wasm binary did you load?

**Comment by delbetu** [comment]
oh, that is the point, I'm not packing with `rbwasm` (I didn't know its existence)
I'm moving files to a local lib folder and mapping the directory with `wasi-vfs pack`
I'll try with `rbwasm`
Thanks!
