### ISSUE TITLE
 null function or function signature mismatch

### ISSUE THREAD

**Issue by davidsiaw** [ruby/ruby.wasm#466]
Thank you for your awesome work getting Ruby to work in the browser. I had a play around and found that after running it for a while it crashes with an issue:

```
Tried to report internal Ruby VM state but failed:  RuntimeError: null function or function signature mismatch
```

You can easily reproduce this bug by using the following file:

https://github.com/davidsiaw/rubywasm-crash/blob/master/public/index.html

And wait for anywhere between 1 minute to 10 minutes.

I attempted to workaround the issue but it seems like once it hits this error it cannot recover, even with a try catch around the `step` function in JS. 

More screenshots:
<detail>
![image](https://github.com/ruby/ruby.wasm/assets/874280/d97a9b87-44c1-4055-b2a8-384a65faf136)

![image](https://github.com/ruby/ruby.wasm/assets/874280/79b62e69-946d-4aa8-89de-97c4466fe386)

**Comment by kateinoigakukun** [comment]
Could you try version [2.6.1-2024-06-14-b](https://www.npmjs.com/package/@ruby/head-wasm-wasi/v/2.6.1-2024-06-14-b)? It includes [a fix around GC issue](https://github.com/ruby/ruby.wasm/commit/b2370f6c5200c7115c887f5b8ad3c282bec33f68)

**Comment by tani** [comment]
I have also seen the similar error message with custom ruby build with rbwasm.
Would you mind giving me the instructions for using the ruby you mentioned?
I guess it could be done by `rbwasm build --ruby-version`. However, I could not complete it.

- https://github.com/tani/asciidoctor-wasm/tree/main

**Comment by kateinoigakukun** [comment]
@tani You just need to upgrade `ruby_wasm` and `js` gem in your Gemfile, and corresponding npm packages. Just published 2.6.2, so you can use it now.

**Comment by tani** [comment]
Great. I now confirm that my issue is solved.
Asciidoctor-wasm works expectedly. Thanks!

**Comment by kateinoigakukun** [comment]
Thank you for your confirmation!
