### ISSUE TITLE
build/toolchain/binaryen/bin/wasm-opt: No such file or directory

### ISSUE THREAD

**Issue by ledsun** [ruby/ruby.wasm#51]
I ran the following command

```sh
rake npm:ruby-head-wasm-wasi
```

The command succeeds.
However, I get an error in the execution log.

```
/home/ledsun/ruby.wasm/packages/npm-packages/ruby-head-wasm-wasi/. /ruby-wasm-wasi/tools/pack-ruby-wasm.sh: line 18: /home/ledsun/ruby.wasm/build/toolchain/binaryen/bin/wasm-opt: no such file or directory
```

And `packages/npm-packages/ruby-head-wasm-wasi/dist/ruby.stdlib.wasm` was not created.

The full execution log can be found at https://gist.github.com/ledsun/b76fb84feb5b6cff97a52ae2fac43d4e .

**Comment by kateinoigakukun** [comment]
Thank you for reporting :)
I hope it has been fixed by https://github.com/ruby/ruby.wasm/commit/a3c501708ca577cb094e3de79da4d9c022bbe5b0 :pray:
